name: Publish Addons

on:
 push:
  branches:
  - main
 pull_request:
  branches:
  - main
env:
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 IS_MAIN: ${{ contains(github.ref, 'main') }}

jobs:
  CleanArtifacts:
    # This job clears out the previous artifacts made so you don't run out of space in your github account
    runs-on: ubuntu-latest
    steps:
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 1hr

  Build:
    needs: CleanArtifacts # wait for artifacts to clean before making a new one
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Build
      run: |
        npm install
        npm run build
    
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
  Release:
    needs: Build
    if: ${{ contains(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify Tag
        if: ${{ !steps.tag_version.outputs.new_tag }}
        run: exit 1
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: build
          path: build
      
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      
      - name: Upload Release Artifact
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "build/*.*"
          tag: ${{ steps.tag_version.outputs.new_tag }}
          overwrite: true
          file_glob: true
      
      - uses: frdrwrt/write-to-file@v1.3
        with:
          filepath: ./VERSION.txt
          content: ${{ steps.tag_version.outputs.new_version }}
          mode: 0655
      
      - uses: actions/upload-artifact@v4
        with:
          name: VERSION
          path: ./VERSION.txt
  Cleanup:
    needs: [Build, Release]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: VERSION
          failOnError: false